const express = require('express')
const oderControllor = require('../controllers/OrderController')
const middlewares = require('../controllers/MiddlewareController')
const router = express.Router()

router.post('/create-order', middlewares.userAccuracy, oderControllor.createOrder)
router.put('/cancel-order/:id', middlewares.userAccuracy, oderControllor.cancelOrder)
router.get('/allorder-byuser/:id', middlewares.UserIdAccuracy, oderControllor.allOrderByUser)
router.get('/rocessing-byuser/:id', middlewares.UserIdAccuracy, oderControllor.rocessingByUser)
router.get('/transport-byuser/:id', middlewares.UserIdAccuracy, oderControllor.transportByUser)
router.get('/delivering-byuser/:id', middlewares.UserIdAccuracy, oderControllor.deliveringByUser)
router.get('/finished-byuser/:id', middlewares.UserIdAccuracy, oderControllor.finishedByUser)
router.get('/cancelled-byuser/:id', middlewares.UserIdAccuracy, oderControllor.cancelledByUser)
router.get('/allorder', middlewares.userAdminAccuracy, oderControllor.allOrder)
router.get('/order-detail/:id', middlewares.userOrAdminAccuracy, oderControllor.orderDetail)
router.put('/transport-update/:id', middlewares.userAdminAccuracy, oderControllor.transportUpdate)
router.put('/delivering-update/:id', oderControllor.deliveringUpdate)
router.put('/delivered-update/:id', oderControllor.deliveredUpdate)
router.put('/unfinished-update/:id', oderControllor.unfinishedUpdate)
router.put('/finished-update/:id', oderControllor.finishedUpdate)
router.get('/all-status/:id', oderControllor.allStatus)
router.get('/all-order-transport', oderControllor.allOrderTransport)
router.get('/all-order-confirm', oderControllor.allOrderConfirm)
router.get('/all-transport', oderControllor.allTransport)
router.get('/all-rocessing', oderControllor.allRocessing)
router.get('/all-unfinished', oderControllor.allUnfinished)
router.get('/all-delivered', oderControllor.allDelivered)


module.exports = router
