const express = require('express')
const productController = require('../controllers/ProductController')
const middlewares = require('../controllers/MiddlewareController')
const upload = require('./upload')
const router = express.Router()

router.post('/add-product', middlewares.userAdminAccuracy, upload.array("image", 12), productController.addProduct)
router.get('/image/:name', productController.getImages)
router.put('/update-product/:id', middlewares.userAdminAccuracy, upload.array("image", 12), productController.updateProduct)
router.delete('/delete-product/:id', middlewares.userAdminAccuracy, productController.deleteProduct)
router.get('/detail-product/:id', productController.getDetailProduct)
router.get('/all-product', productController.getAllProduct)
router.post('/create-type', middlewares.userAdminAccuracy, productController.createType)
router.get('/getall-type', productController.getAllType)
router.get('/get-type-by-father', productController.getTypeByFather)
router.delete('/delete-type/:id', middlewares.userAdminAccuracy, productController.deleteType)
router.put('/update-type/:id', middlewares.userAdminAccuracy, productController.updateType)
router.get('/detail-type/:id', middlewares.userAdminAccuracy, productController.getDetailType)
router.get('/all-size', productController.getAllSize)
router.get('/all-type', productController.allTypeNotSearch)
router.get('/random-products', productController.randomProduct)
router.get('/filter-by-type/:id', productController.filterByType)
router.get('/filter-all', productController.filterAll)


module.exports = router